### ISSUE TITLE
Лутбоксы

### ISSUE THREAD

**Issue by yury-legacy** [akulenkoArtem/akulenkoArtem.github.io#2]
Добавьте, _пожалуйста_, **лутбоксы**!!!!!

**Comment by akulenkoArtem** [comment]
Здравствуйте, нужно более конкретное ТЗ.
Что должно быть в лутбоксах?

**Comment by yury-legacy** [comment]
Думаю, там должны быть скины, купоны и всякие power-ups

**Comment by yury-legacy** [comment]
Спасибо аз труд, но ваш проект скатился. Я ухожу
